<?php
if ($this->modules->count() === 0) {
    ?>
    <div class="alert alert-info alert-block"><?php echo $this->translate('You have not added any modules'); ?></div>
    <?php
}
foreach ($this->modules as $module) {
    echo $this->moduleView([
        'id' => $module->getId(),
        'owner' => $module->getOwner(),
        'name' => $module->getName(),
        'created_at' => $module->getCreatedAt(),
        'url' => $module->getUrl(),
        'photo_url' => $module->getPhotoUrl(),
        'description' => $module->getDescription(),
    ], 'remove');
}
